### ISSUE TITLE
Static Site Generatorの切り替え(Hexo -> Hugo)

### ISSUE THREAD

**Issue by sperkbird** [histudy/site#31]
インフラ基盤更改に合わせ、SSGの依存関係での脆弱性対応削減のため
HexoからHugoへ切り替える対応を実施する。

切り替えにあたり下記対応が必要な見込み
* 切り替え対応のブランチ作成
* コンフィグファイルのHugo向け変換
* 記事のヘッダ部分のHugo向け変換

**Comment by akiya64** [comment]
Hugo のテーマを適当に見つくろって、まずは表示できる状態を目指します。
候補： [Binario - Theme Info](https://jamstackthemes.dev/theme/hugo-binario/)

> 切り替え対応のブランチ作成

フォークしたので、それで一先ず進めていきます。

> コンフィグファイルのHugo向け変換

Hugo で生成したコンフィグに書き写していく形になりそうです。
設定項目はテーマにもよるため。

> 記事のヘッダ部分のHugo向け変換

こちらは機械的に置換でいけると思います。

**Comment by akiya64** [comment]
http://test.histudy.jp/  
テスト用のサーバができまして、レビュー用にHugoで生成したHTML入れてます。

## 修正

- [x]  `lineheight` 1.8 ぐらいに、詰まって見える。
- [x] フロントページの「もっと見る」がフルパスのためリンクが機能しない
- [x] 各ページのタグのリンク先が404
- [x] ヘッダーメニューの開催履歴が404

## その他

- 元のマークダウンファイルのリストのインデントの位置によって、HTMLでは意図せずリストが入れ子になる模様

**Comment by akiya64** [comment]
> 日本語フォルダ、ファイルが404

WinSCPでSCP転送するとき、WinSCPの設定で「UTF-8 に変換する」をONにしてないと文字化けするため。
「自動」だと駄目。

**Comment by akiya64** [comment]
> HTMLでは意図せずリストが入れ子になる

マークダウンのリストとリストの間に空行があると下記のように、意図しない `<p>` タグが挿入されて、リストの第一要素直下に意図しないマージンが発生する。

```
<ul>
  <li><p>リスト要素</p>
    <ul>
       ...
    <ul>
  </li>
</ul>
```

**Comment by akiya64** [comment]
CircleCI の Hugo ビルド用イメージ
[CircleCI Developer Hub - circleci/hugo](https://circleci.com/developer/orbs/orb/circleci/hugo)

**Comment by akiya64** [comment]
6b66eb6304ca9541d013f7e8e75468d79811845a にてPRをマージ
