### ISSUE TITLE
github に依存ライブラリに脆弱性警告されているので対応を検討する

### ISSUE THREAD

**Issue by fu7mu4** [histudy/site#32]
https://github.com/histudy/site/security/dependabot

**Comment by sperkbird** [comment]
インフラ更改の対応の中でHexoからHugoに移行予定のため、最終的には対応せずHexo利用停止に伴ってCloseさせて頂く予定です
参考:インフラ更改の該当Issue
https://github.com/histudy/infra-replace/issues/6

**Comment by akiya64** [comment]
Hugo に切り替えて、dependapod による PR は全てクローズ。  
Hugo のテーマ内の package.json に反応するため、dependabot を停止しました。
